version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nova_aplicacao_postgres
    environment:
      POSTGRES_DB: nova_aplicacao_db
      POSTGRES_USER: nova_user
      POSTGRES_PASSWORD: nova_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - nova_aplicacao_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: nova_aplicacao_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nova_aplicacao_network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nova_aplicacao_backend
    environment:
      - DATABASE_URL=postgresql://nova_user:nova_password@postgres:5432/nova_aplicacao_db
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-jwt-key-change-this-in-production}
      - APP_ENVIRONMENT=production
      - APP_DEBUG=false
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - nova_aplicacao_network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nova_aplicacao_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_APP_NAME=Nova Aplicação
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - nova_aplicacao_network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: nova_aplicacao_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - nova_aplicacao_network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  nova_aplicacao_network:
    driver: bridge
